version: '3.8'
services:
  animal-frontend:
    container_name: animal-noises_animal-frontend
    image: htrvolker/animal-frontend:${app_version}
    build: ./service_1
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: ${replicas}
  animal-backend:
    container_name: animal-noises_animal-backend
    image: htrvolker/animal-backend:${app_version}
    build: ./service_2
    deploy:
      replicas: ${replicas}